### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sudonto** [LevinJ/SSD_tensorflow_VOC#18]
I have error when running training_model.py. The message is:

Traceback (most recent call last):
  File "D:\Workspace\DL\SSD\train_net.py", line 281, in <module>
    obj.run()
  File "D:\Workspace\DL\SSD\train_net.py", line 241, in run
    image, glabels, gbboxes, gdifficults, gclasses, localizations, gscores = self.get_voc_2007_train_data()
ValueError: too many values to unpack (expected 7)

So, how is the solution? I am newbie in python/tensorflow. Thank you.

**Comment by LevinJ** [comment]
Hi @sudonto, the training script should run fine.

Regarding the error you are observing, I think it's complaining that `self.get_voc_2007_train_data()` is not returning a list of 7 elements as expected.  Did you put the data file in proper folders?

the readme file has detailed steps on how to generate tfrecords and run training scripts, hope it helps.


https://github.com/LevinJ/SSD_tensorflow_VOC
