### ISSUE TITLE
Training Instructions

### ISSUE THREAD

**Issue by alberto139** [LevinJ/SSD_tensorflow_VOC#5]
I'm trying to train the model on Pascal VOC.
I downloaded the dataset and converted them into TFRecords following the instructions on the README. 

However I'm a little confused about how to train. My `tfrecords` files are in the `./datasets` folder. 
My `./logs` folder has a `fine-tune` subfolder which is empty with the exception of some `events.out.tfevent` files that get created every time I attempt to train. 

I'm not sure what I'm missing. Am I supposed to have some retrained ImageNets weights somewhere? 

Any help is appreciated!

Here is my error message:

```
$ python ./train_model.py
INFO:tensorflow:Fine-tuning from None
INFO:tensorflow:Restoring parameters from None
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, Unable to get element from the feed as bytes.
Traceback (most recent call last):
  File "./train_model.py", line 435, in <module>
    obj.run()
  File "./train_model.py", line 427, in run
    self.__start_training()
  File "./train_model.py", line 222, in __start_training
    save_interval_secs=self.save_interval_secs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 732, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 953, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 708, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    init_fn(sess)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 654, in callback
    saver.restore(session, model_path)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'init_ops/report_uninitialized_variables/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "./train_model.py", line 435, in <module>\n    obj.run()', 'File "./train_model.py", line 427, in run\n    self.__start_training()', 'File "./train_model.py", line 222, in __start_training\n    save_interval_secs=self.save_interval_secs)', 'File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 655, in train\n    ready_op = tf_variables.report_uninitialized_variables()', 'File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py", line 170, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py", line 139, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py", line 96, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']
==================================
```

**Comment by LevinJ** [comment]
Hi @alberto139, yes, you will need to download the pretrained vgg16 weights, please see the updated readme for more details.

**Comment by alberto139** [comment]
Thanks @LevinJ! I was able to train the model by following the readme.

**Comment by LevinJ** [comment]
That sounds great.  @alberto139, do share with me if you find means to push the mAP beyond current 0.65 :)
